scrape_configs:
  - job_name: 'postgres-exporter'
    static_configs:
       - targets: [ 'postgres_exporter:9187' ]
  - job_name: 'simulator-app'
    scrape_interval: 10s
    static_configs:
       - targets: [ 'simulator:6969' ]