{
 "title": "SamokAaht",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Среднее время выполнения каждого запроса за последнюю минуту",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(query_in_seconds_sum{job=\"simulator-app\"}[1m]) \n/ \nrate(query_in_seconds_count{job=\"simulator-app\"}[1m])",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "График среднего времени выполнения каждого из запросов",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(query_in_seconds_sum{job=\"simulator-app\"}[1m]) \n/ \nrate(query_in_seconds_count{job=\"simulator-app\"}[1m])",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Процент использования каждого индекса",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "index_usage_stats_index_usage_percent",
     "legendFormat": "{{index_name}}"
    }
   ]
  },
  {
   "title": "Количество выполнений каждого из запросов",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    { "expr": "queries_executed_total", "legendFormat": "{{query}}" }
   ]
  }
 ]
}