name: SamokAaht CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_idempotency_of_migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check Docker and Docker Compose
        run: |
          docker version
          docker compose version

      - name: Run idempotency migration tests
        run: |
          cd test
          chmod +x test_migrations.sh
          ./test_migrations.sh
        env:
          TEST_PORT: ${{ secrets.TEST_PORT }}
          TEST_POSTGRES_DB: ${{ secrets.TEST_POSTGRES_DB }}
          TEST_POSTGRES_USER: ${{ secrets.TEST_POSTGRES_USER }}
          TEST_POSTGRES_PASSWORD: ${{ secrets.TEST_POSTGRES_PASSWORD }}