name: SamokAaht CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ "seeding", "simulator", "test" ]
      fail-fast: false
      max-parallel: 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache golangci-lint
        uses: actions/cache@v3
        with:
          path: ~/.cache/golangci-lint
          key: ${{ runner.os }}-golangci-lint

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.9'
          cache: true

      - name: Lint Go code in ${{ matrix.module }}
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.60.3
          args: --timeout=5m -v --config=../.github/.golangci.yml
          working-directory: ${{ matrix.module }}

  test_idempotency_of_migrations:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check Docker and Docker Compose
        run: |
          docker version
          docker compose version

      - name: Run idempotency migration tests
        run: |
          cd test
          chmod +x test_migrations.sh
          ./test_migrations.sh
        env:
          TEST_PORT: ${{ secrets.TEST_PORT }}
          TEST_POSTGRES_DB: ${{ secrets.TEST_POSTGRES_DB }}
          TEST_POSTGRES_USER: ${{ secrets.TEST_POSTGRES_USER }}
          TEST_POSTGRES_PASSWORD: ${{ secrets.TEST_POSTGRES_PASSWORD }}