name: SamokAaht CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ "seeding", "simulator", "test" ]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.9'
          cache: false

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ${{ matrix.module }}/go.sum
          key: ${{ runner.os }}_${{ matrix.module }}${{ hashFiles('${{ matrix.module }}/go.sum') }}
          restore-keys: |
            ${{ runner.os }}_${{ matrix.module }}
        continue-on-error: true

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.60.3

      - name: Lint Go code in ${{ matrix.module }}
        run: |
          cd ${{ matrix.module }}
          golangci-lint run --timeout=5m -v --config ../.github/.golangci.yml

  test_idempotency_of_migrations:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check Docker and Docker Compose
        run: |
          docker version
          docker compose version

      - name: Run idempotency migration tests
        run: |
          cd test
          chmod +x test_migrations.sh
          ./test_migrations.sh
        env:
          TEST_PORT: ${{ secrets.TEST_PORT }}
          TEST_POSTGRES_DB: ${{ secrets.TEST_POSTGRES_DB }}
          TEST_POSTGRES_USER: ${{ secrets.TEST_POSTGRES_USER }}
          TEST_POSTGRES_PASSWORD: ${{ secrets.TEST_POSTGRES_PASSWORD }}